# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-02 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_shirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
