# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-02 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190402_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shirt_size',
        ),
    ]
