# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-02 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shirt_size',
        ),
    ]
